version: '2'
services:
    consul:
        image: localhost:5000/consul:latest
        hostname: consul
        ports:
          - "8400:8400"
          - "8500:8500"
          - "8600:8600"
        command: "agent -dev -client=0.0.0.0 -ui"

    microservice:
        image: localhost:5000/bytewood/ops/microservice:latest
        env_file:
          - ./environment/microservice.env

    microservice-a:
        image: localhost:5000/bytewood/ops/microservice-a:latest
        env_file:
          - ./environment/microservice-a.env

