version: '2'
services:
    consul:
        image: ${REGISTRY_URL}/consul:0.7.0
        hostname: consul
        volumes:
            - /data/logs/consul:/logs:rw
        ports:
            - "8500:8500"
        command: "agent -dev -client=0.0.0.0 -ui -log-level info "

    logstash:
        image: logstash:5.0.0
        ports:
            - "9100:9100"
            - "9101:9101"
            - "9102:9102"
        volumes:
            - ./logstash/config:/config
            - ./logstash/patterns:/patterns
        environment:
            LS_SETTINGS_DIR: /config
        command: [ "-f", "/config/logstash-filebeat.conf", "-r", "--log.level", "info" ]

    elastic:
        image: elasticsearch:5.0.0
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - /data/elasticsearch:/usr/share/elasticsearch/data
    
    kibana:
        image: kibana:5.0.0
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_URL: http://elastic:9200

    filebeat:
        image: bytewood/filebeat:5.0.0
        volumes:
            - /data/logs:/var/log
            - ./filebeat/etc/filebeat-logstash.yml:/etc/filebeat.yml
        entrypoint:
            - filebeat
            - -c
            - /etc/filebeat.yml
        

