version: '2'
services:
    consul:
        image: ${REGISTRY_URL}/consul:latest
        hostname: consul
        ports:
            - "8500:8500"
        command: "agent -dev -client=0.0.0.0 -ui"
        logging:
          driver: syslog
          options:
            syslog-address: "tcp://logstash:9100"
            tag: consulate

    logstash:
        image: logstash
        ports:
            - "9100:9100"
        volumes:
            - ./logstash:/config
        command: [ "-f", "/config/syslog-to-elastic.conf", "--auto-reload" ]

    elastic:
        image: elastic-marvel
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - /data:/usr/share/elasticsearch/data
    
    kibana:
        depends_on:
            - elastic
        image: kibana-marvel
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_URL: http://elastic:9200

