version: '2'
services:
    consul:
        image: ${REGISTRY_URL}/consul:latest
        hostname: consul
        ports:
            - "8400:8400"
            - "8500:8500"
            - "8600:8600"
        command: "agent -dev -client=0.0.0.0 -ui -log-level debug"

    microservice:
        depends_on:
            - consul
        image: ${REGISTRY_URL}/bytewood/ops-microservice:0.1.0.14
        ports:
            - "8881:8881"
        env_file:
            - ./environment/microservice.env
        volumes:
            - ./environment/uat:/config:ro
        entrypoint:
            - java
            - -Dspring.profiles.active=consul
            - -jar
            - /app.jar

    microservice-a:
        depends_on:
            - consul
        image: ${REGISTRY_URL}/bytewood/ops-microservice-a:0.1.0.3
        ports:
            - "8882:8882"
        env_file:
            - ./environment/microservice-a.env
        entrypoint:
            - java
            - -Dspring.profiles.active=consul
            - -jar
            - /app.jar

