version: '2'
services:
    consul:
        depends_on:
            - logstash
        image: ${REGISTRY_URL}/consul:0.7.0
        hostname: consul
        logging:
          driver: syslog
          options:
            syslog-address: "tcp://logstash:9102"
            tag: "consul|{{.Name}}|{{.FullID}}|{{.ImageName}}|{{.ImageFullID}}"
        ports:
            - "8500:8500"
        command: "agent -dev -client=0.0.0.0 -ui -log-level info"

    logstash:
        depends_on:
            - elastic
        image: logstash:5.0.0
        ports:
            - "9100:9100"
            - "9101:9101"
            - "9102:9102"
        volumes:
            - ./logstash/config:/config
            - ./logstash/patterns:/patterns
        environment:
            LS_SETTINGS_DIR: /config
        command: [ "-f", "/config/syslog-to-elastic.conf", "-r", "--log.level", "info" ]

    elastic:
        image: elasticsearch:5.0.0
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - /data/elasticsearch:/usr/share/elasticsearch/data
    
    kibana:
        depends_on:
            - elastic
        image: kibana:5.0.0
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_URL: http://elastic:9200

