version: '2'
services:
    consul:
        image: ${REGISTRY_URL}/consul:latest
        hostname: consul
        ports:
            - "8500:8500"
        command: "agent -dev -client=0.0.0.0 -ui"

    logstash:
        image: logstash
        ports:
            - "9100:9100"
        volumes:
            - ./logstash:/config
        command: [ -f /config/syslog-to-elastic.conf ]

    elastic:
        image: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - /data:/usr/share/elasticsearch/data
    
    kibana:
        depends_on:
            - elastic
        image: kibana
        ports:
            - "5601:5601"

    microservice:
        image: ${REGISTRY_URL}/bytewood/ops-microservice:0.1.0.27
        ports:
            - "8881:8080"
        env_file:
            - ./environment/microservice.env
        volumes:
            - ./environment/uat/_scripts:/scripts
            - ./environment/uat/microservice:/config
        entrypoint:
            - "java"
            - "-jar"
            - "app.jar"
            - "--spring.config.location=file:/config/"
            - "--spring.profiles.active=consul"
    microservice-a:
        depends_on:
            - consul
        image: ${REGISTRY_URL}/bytewood/ops-microservice-a:0.1.0.18
        ports:
            - "8882:8080"
        env_file:
            - ./environment/microservice-a.env
        volumes:
            - ./environment/uat/_scripts:/scripts
            - ./environment/uat/microservice-a:/config
        entrypoint:
            - "java"
            - "-jar"
            - "/app.jar"
            - "--spring.config.location=file:/config/"
            - "--spring.profiles.active=consul"


