version: '2'
services:
    consul:
        image: ${REGISTRY_URL}/consul:latest
        hostname: consul
        ports:
            - "8400:8400"
            - "8500:8500"
            - "8600:8600"
        entrypoint:
            - "agent"
            - "-dev"
            - "-client=0.0.0.0"
            - "-ui"
            - "-log-level"
            - " debug"

    microservice:
        image: bytewood/ops-gradle:latest
        ports:
            - "8881:8080"
        env_file:
            - ../environment/microservice.env
        volumes:
            - "/media/data/projects/bytewood/ops/microservice:/app"
            - "/home/peter/.gradle:/root/.gradle"
        working_dir: /app
        extra_hosts: 
            - "artifactory:$HOST_IP"
        entrypoint:
            - "gradle"
            - "--offline"
            - "-PSPRING_PROFILES_ACTIVE=consul"
            - "bootRun"
    microservice-a:
        depends_on:
            - consul
        image: bytewood/ops-gradle:latest
        ports:
            - "8882:8080"
        env_file:
            - ../environment/microservice-a.env
        volumes:
            - "/media/data/projects/bytewood/ops/microservice-a:/app"
            - "/home/peter/.gradle:/root/.gradle"
        working_dir: /app
        extra_hosts:
            - "artifactory:$HOST_IP"
        entrypoint:
            - "gradle"
            - "--offline"
            - "-PSPRING_PROFILES_ACTIVE=consul"
            - "bootRun"


