version: '2'
services:
    consul:
        image: ${REGISTRY_URL}/consul:0.7.0
        hostname: consul
        ports:
            - "8500:8500"
        entrypoint:
            - "agent"
            - "-dev"
            - "-client=0.0.0.0"
            - "-ui"

    microservice:
        image: bytewood/ops-gradle:latest
        ports:
            - "8881:8881"
        env_file:
            - ../environment/microservice.env
        volumes:
            - "/media/data/projects/bytewood/ops/microservice:/app"
            - "/home/peter/.gradle:/root/.gradle"
        working_dir: /app
        extra_hosts: 
            - "artifactory:$HOST_IP"
        entrypoint:
            - "gradle"
            - "--offline"
            - "-PSPRING_PROFILES_ACTIVE=consul"
            - "bootRun"
    microservice-a:
        depends_on:
            - consul
        image: ${REGISTRY_URL}/bytewood/ops-microservice-a:0.1.0.18
        ports:
            - "8882:8882"
        entrypoint:
            - java
            - -jar
            - /app.jar
            - --spring.profiles.active=consul
            - --debug

