management:
  contextPath: /system
spring:
  application:
    name: microservice-a
server:
  port: 8080
  contextPath: /
abc:
  abc: "${ABC:pqr}"
logging:
  file: /logs/${spring.application.name}.log

