spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        healthCheckPath: ${management.contextPath}/health
        healthCheckInterval: 13s
        instanceId: ${spring.application.name}:${HOSTNAME:${random.value}}
      retry:
        initialInterval: 3000
        maxInterval: 15000
        maxAttempts: 30
