management:
  contextPath: /system
spring:
  application:
    name: microservice
server:
  port: 8080
  contextPath: /
abc:
  abc: "${ABC:abc}"
microservice-a:
  protocol: http
  ip: microservice-a
  port: 8080
  context: /
logging:
  file: /data/logs/${spring.application.name}.log

